baseURL = "https://smartgearhub.netlify.app/"
languageCode = "es"
title = "SmartGearHub"
theme = "PaperMod"
pagerSize = 10

[params]
  description = "SmartGearHub: tu guía confiable para comparar tecnología, gadgets inteligentes y soluciones de energía moderna."
  keywords = ["tecnología", "gadgets", "reseñas", "comparativas", "hogar inteligente", "routers", "energía solar"]
  author = "SmartGearHub"
  defaultTheme = "light"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  comments = false
  env = "production"

[params.analytics.google]
  SiteVerificationTag = "S8CwUyDsEun_cdnZ5ZC0EeF33z212gHg1vQX0Is-JNY"

[params.footer]
  text = "SmartGearHub participa en el Programa de Afiliados de Amazon. Como afiliado, puedo recibir comisiones por compras calificadas realizadas a través de los enlaces de este sitio."
  hideCopyright = false
  showThemeCredit = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menu.main]]
  name = "Inicio"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Reseñas"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Comparativas"
  url = "/tags/comparativa/"
  weight = 3

[[menu.main]]
  name = "Guías"
  url = "/tags/guia/"
  weight = 4

[sitemap]
  changefreq = "weekly"
  priority = 0.8
  filename = "sitemap.xml"